# Generated by Django 3.1.14 on 2022-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20221010_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons_images/', verbose_name='Изображение покемона'),
        ),
    ]
