# Generated by Django 3.1.14 on 2022-10-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20221010_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Эволюционировал от'),
        ),
    ]
