# Generated by Django 3.1.14 on 2022-10-11 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20221011_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
    ]
