# Generated by Django 3.1.14 on 2022-10-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_auto_20221014_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=200, verbose_name='Заголовок на Русском'),
        ),
    ]
